version: 0.{build}
pull_requests:
  do_not_increment_build_number: true

# After a PR is opened, don't run separate appveyor builds for the branch - only builds for the PR.
skip_branch_with_pr: true

os: Windows Server 2012 R2

# Custom clone folder (variables are not expanded here).
clone_folder: c:\influxdb

# Environment variables
environment:
  GOROOT: C:\go111
  GOFLAGS: "-mod=readonly"

# Scripts that run after cloning repository
install:
#  - choco install bzr # Needed to install go modules
 - set PATH=%GOROOT%\bin;%GOPATH%\bin;C:\Program Files (x86)\Bazaar\;%PATH%
 - echo %PATH%
 - echo %GOPATH%
 - cd C:\influxdb
 - go version
 - go env

build: false
deploy: false

test_script:
  - echo "Appveyor needs to be re-enabled. See https://github.com/influxdata/influxdb/issues/10937"
  # - go test -timeout 15m -v ./...
